import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { createCatalogEntries, parseCsv } from '../src/lib/catalog/normalize';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');
const csvPath = path.join(rootDir, 'LIST OBAT 2026.csv');
const outputDir = path.join(rootDir, 'src', 'generated');
const outputPath = path.join(outputDir, 'catalog.ts');

async function main(): Promise<void> {
  const raw = await readFile(csvPath, 'utf8');
  const rows = parseCsv(raw);
  const entries = createCatalogEntries(rows);

  const body = `// Generated by scripts/buildCatalog.ts. Do not edit manually.
import type { CatalogEntry } from '../lib/catalog/types';

export const catalogEntries: CatalogEntry[] = ${JSON.stringify(entries, null, 2)} as CatalogEntry[];
`;

  await mkdir(outputDir, { recursive: true });
  await writeFile(outputPath, body, 'utf8');
  process.stdout.write(`Generated ${entries.length} catalog entries to ${outputPath}\n`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
