import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CSV_PATH = resolve(ROOT, 'LIST OBAT 2026.csv');
const GENERATED_PATH = resolve(ROOT, 'src/generated/catalog.ts');

const MAX_TEMPLATE_DATA_ROWS = 30;
const MAX_GENERATED_ENTRIES = 30;

const SUSPICIOUS_DRUG_KEYWORDS = [
  'paracetamol',
  'amoxicillin',
  'ibuprofen',
  'cetirizine',
  'omeprazole',
  'metformin',
  'dexamethasone',
  'salbutamol',
  'azithromycin',
  'chlorpheniramine'
];

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function findSuspiciousKeywords(content: string): string[] {
  return SUSPICIOUS_DRUG_KEYWORDS.filter((keyword) => {
    const pattern = new RegExp(`\\b${escapeRegExp(keyword)}\\b`, 'i');
    return pattern.test(content);
  });
}

function checkCsv(csvRaw: string): string[] {
  const failures: string[] = [];
  const lines = csvRaw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);

  if (lines.length === 0) {
    failures.push('CSV kosong.');
    return failures;
  }

  const header = lines[0];
  if (header !== 'Kategori,Kandungan,Sediaan,Obat BPJS,Obat Umum') {
    failures.push('Header CSV tidak sesuai template yang diharapkan.');
  }

  const dataRows = lines.slice(1);
  if (dataRows.length > MAX_TEMPLATE_DATA_ROWS) {
    failures.push(
      `Jumlah baris data CSV ${dataRows.length} melebihi batas template ${MAX_TEMPLATE_DATA_ROWS}.`
    );
  }

  for (const [index, line] of dataRows.entries()) {
    const rowNumber = index + 2;
    const cells = line.split(',');
    const kategori = cells[0] ?? '';

    if (!kategori.startsWith('TEMPLATE ')) {
      failures.push(`Baris ${rowNumber}: kolom Kategori harus diawali "TEMPLATE ".`);
    }

    if (!line.includes('Komponen ')) {
      failures.push(`Baris ${rowNumber}: konten kandungan tidak terlihat sebagai template.`);
    }

    if (!line.includes('OBAT-CONTOH-')) {
      failures.push(`Baris ${rowNumber}: alias obat tidak terlihat sebagai placeholder template.`);
    }
  }

  const suspiciousKeywords = findSuspiciousKeywords(csvRaw);
  if (suspiciousKeywords.length > 0) {
    failures.push(
      `CSV mengandung kata obat nyata yang diblokir: ${suspiciousKeywords.join(', ')}.`
    );
  }

  return failures;
}

function checkGenerated(generatedRaw: string): string[] {
  const failures: string[] = [];

  if (!generatedRaw.includes('// Generated by scripts/buildCatalog.ts. Do not edit manually.')) {
    failures.push('catalog.ts kehilangan header generated file.');
  }

  const entryMatches = generatedRaw.match(/"id":\s*"catalog-\d+"/g) ?? [];
  if (entryMatches.length > MAX_GENERATED_ENTRIES) {
    failures.push(
      `Jumlah entry generated ${entryMatches.length} melebihi batas template ${MAX_GENERATED_ENTRIES}.`
    );
  }

  if (!generatedRaw.includes('OBAT-CONTOH-')) {
    failures.push('catalog.ts tidak mengandung placeholder alias OBAT-CONTOH-.');
  }

  const suspiciousKeywords = findSuspiciousKeywords(generatedRaw);
  if (suspiciousKeywords.length > 0) {
    failures.push(
      `catalog.ts mengandung kata obat nyata yang diblokir: ${suspiciousKeywords.join(', ')}.`
    );
  }

  return failures;
}

function main(): void {
  const csvRaw = readFileSync(CSV_PATH, 'utf8');
  const generatedRaw = readFileSync(GENERATED_PATH, 'utf8');

  const csvFailures = checkCsv(csvRaw);
  const generatedFailures = checkGenerated(generatedRaw);
  const failures = [...csvFailures.map((item) => `[CSV] ${item}`), ...generatedFailures.map((item) => `[Generated] ${item}`)];

  if (failures.length > 0) {
    console.error('❌ Catalog sanitization check failed:');
    for (const failure of failures) {
      console.error(` - ${failure}`);
    }
    process.exit(1);
  }

  console.log('✅ Catalog sanitization check passed.');
}

main();
